// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/lumos_server/lumos_server.proto)

#include <iomanip>

#include "lumos_server_impl.h"
#include "plugins/lumos_server/lumos_server.h"

namespace mavsdk {

using Dance = LumosServer::Dance;
using Position = LumosServer::Position;
using GlobalPosition = LumosServer::GlobalPosition;
using Coord = LumosServer::Coord;
using Params = LumosServer::Params;

using DroneInfo = LumosServer::DroneInfo;
using CompanionStatus = LumosServer::CompanionStatus;

LumosServer::LumosServer(std::shared_ptr<ServerComponent> server_component) :
    ServerPluginBase(),
    _impl{std::make_unique<LumosServerImpl>(server_component)}
{}

LumosServer::~LumosServer() {}

void LumosServer::set_drone_info(DroneInfo drone_info) const
{
    _impl->set_drone_info(drone_info);
}

void LumosServer::set_companion_status(CompanionStatus drone_info) const
{
    _impl->set_companion_status(drone_info);
}

LumosServer::DanceHandle LumosServer::subscribe_dance(const DanceCallback& callback)
{
    return _impl->subscribe_dance(callback);
}

void LumosServer::unsubscribe_dance(DanceHandle handle)
{
    _impl->unsubscribe_dance(handle);
}

LumosServer::Dance LumosServer::dance() const
{
    return _impl->dance();
}

LumosServer::ParamsHandle LumosServer::subscribe_params(const ParamsCallback& callback)
{
    return _impl->subscribe_params(callback);
}

void LumosServer::unsubscribe_params(ParamsHandle handle)
{
    _impl->unsubscribe_params(handle);
}

LumosServer::Params LumosServer::params() const
{
    return _impl->params();
}

LumosServer::StartHandle LumosServer::subscribe_start(const StartCallback& callback)
{
    return _impl->subscribe_start(callback);
}

void LumosServer::unsubscribe_start(StartHandle handle)
{
    _impl->unsubscribe_start(handle);
}

int32_t LumosServer::start() const
{
    return _impl->start();
}

LumosServer::LocalPosHandle LumosServer::subscribe_local_pos(const LocalPosCallback& callback)
{
    return _impl->subscribe_local_pos(callback);
}

void LumosServer::unsubscribe_local_pos(LocalPosHandle handle)
{
    _impl->unsubscribe_local_pos(handle);
}

LumosServer::Position LumosServer::local_pos() const
{
    return _impl->local_pos();
}

LumosServer::GlobalPosHandle LumosServer::subscribe_global_pos(const GlobalPosCallback& callback)
{
    return _impl->subscribe_global_pos(callback);
}

void LumosServer::unsubscribe_global_pos(GlobalPosHandle handle)
{
    _impl->unsubscribe_global_pos(handle);
}

LumosServer::GlobalPosition LumosServer::global_pos() const
{
    return _impl->global_pos();
}

bool operator==(const LumosServer::Dance& lhs, const LumosServer::Dance& rhs)
{
    return (rhs.data == lhs.data) && (rhs.len == lhs.len);
}

std::ostream& operator<<(std::ostream& str, LumosServer::Dance const& dance)
{
    str << std::setprecision(15);
    str << "dance:" << '\n' << "{\n";
    str << "    data: [";
    for (auto it = dance.data.begin(); it != dance.data.end(); ++it) {
        str << *it;
        str << (it + 1 != dance.data.end() ? ", " : "]\n");
    }
    str << "    len: " << dance.len << '\n';
    str << '}';
    return str;
}

bool operator==(const LumosServer::Position& lhs, const LumosServer::Position& rhs)
{
    return ((std::isnan(rhs.x) && std::isnan(lhs.x)) || rhs.x == lhs.x) &&
           ((std::isnan(rhs.y) && std::isnan(lhs.y)) || rhs.y == lhs.y) &&
           ((std::isnan(rhs.z) && std::isnan(lhs.z)) || rhs.z == lhs.z);
}

std::ostream& operator<<(std::ostream& str, LumosServer::Position const& position)
{
    str << std::setprecision(15);
    str << "position:" << '\n' << "{\n";
    str << "    x: " << position.x << '\n';
    str << "    y: " << position.y << '\n';
    str << "    z: " << position.z << '\n';
    str << '}';
    return str;
}

bool operator==(const LumosServer::GlobalPosition& lhs, const LumosServer::GlobalPosition& rhs)
{
    return ((std::isnan(rhs.lat) && std::isnan(lhs.lat)) || rhs.lat == lhs.lat) &&
           ((std::isnan(rhs.lon) && std::isnan(lhs.lon)) || rhs.lon == lhs.lon) &&
           ((std::isnan(rhs.alt) && std::isnan(lhs.alt)) || rhs.alt == lhs.alt);
}

std::ostream& operator<<(std::ostream& str, LumosServer::GlobalPosition const& global_position)
{
    str << std::setprecision(15);
    str << "global_position:" << '\n' << "{\n";
    str << "    lat: " << global_position.lat << '\n';
    str << "    lon: " << global_position.lon << '\n';
    str << "    alt: " << global_position.alt << '\n';
    str << '}';
    return str;
}

bool operator==(const LumosServer::Coord& lhs, const LumosServer::Coord& rhs)
{
    return ((std::isnan(rhs.x) && std::isnan(lhs.x)) || rhs.x == lhs.x) &&
           ((std::isnan(rhs.y) && std::isnan(lhs.y)) || rhs.y == lhs.y);
}

std::ostream& operator<<(std::ostream& str, LumosServer::Coord const& coord)
{
    str << std::setprecision(15);
    str << "coord:" << '\n' << "{\n";
    str << "    x: " << coord.x << '\n';
    str << "    y: " << coord.y << '\n';
    str << '}';
    return str;
}

bool operator==(const LumosServer::Params& lhs, const LumosServer::Params& rhs)
{
    return ((std::isnan(rhs.lon) && std::isnan(lhs.lon)) || rhs.lon == lhs.lon) &&
           ((std::isnan(rhs.lat) && std::isnan(lhs.lat)) || rhs.lat == lhs.lat) &&
           ((std::isnan(rhs.alt) && std::isnan(lhs.alt)) || rhs.alt == lhs.alt) &&
           (rhs.gps_start == lhs.gps_start) &&
           ((std::isnan(rhs.gf_alt) && std::isnan(lhs.gf_alt)) || rhs.gf_alt == lhs.gf_alt) &&
           (rhs.vertices == lhs.vertices);
}

std::ostream& operator<<(std::ostream& str, LumosServer::Params const& params)
{
    str << std::setprecision(15);
    str << "params:" << '\n' << "{\n";
    str << "    lon: " << params.lon << '\n';
    str << "    lat: " << params.lat << '\n';
    str << "    alt: " << params.alt << '\n';
    str << "    gps_start: " << params.gps_start << '\n';
    str << "    gf_alt: " << params.gf_alt << '\n';
    str << "    vertices: [";
    for (auto it = params.vertices.begin(); it != params.vertices.end(); ++it) {
        str << *it;
        str << (it + 1 != params.vertices.end() ? ", " : "]\n");
    }
    str << '}';
    return str;
}

std::ostream& operator<<(std::ostream& str, LumosServer::Result const& result)
{
    switch (result) {
        case LumosServer::Result::Success:
            return str << "Success";
        case LumosServer::Result::Error:
            return str << "Error";
        default:
            return str << "Unknown";
    }
}

bool operator==(const LumosServer::DroneInfo& lhs, const LumosServer::DroneInfo& rhs)
{
    return (rhs.uuid == lhs.uuid) && (rhs.fw_major == lhs.fw_major) &&
           (rhs.fw_minor == lhs.fw_minor) && (rhs.fw_patch == lhs.fw_patch);
}

std::ostream& operator<<(std::ostream& str, LumosServer::DroneInfo const& drone_info)
{
    str << std::setprecision(15);
    str << "drone_info:" << '\n' << "{\n";
    str << "    uuid: " << drone_info.uuid << '\n';
    str << "    fw_major: " << drone_info.fw_major << '\n';
    str << "    fw_minor: " << drone_info.fw_minor << '\n';
    str << "    fw_patch: " << drone_info.fw_patch << '\n';
    str << '}';
    return str;
}

bool operator==(const LumosServer::CompanionStatus& lhs, const LumosServer::CompanionStatus& rhs)
{
    return (rhs.dance_status == lhs.dance_status) && (rhs.rssi_wifi == lhs.rssi_wifi) &&
           (rhs.rssi_xbee == lhs.rssi_xbee);
}

std::ostream& operator<<(std::ostream& str, LumosServer::CompanionStatus const& companion_status)
{
    str << std::setprecision(15);
    str << "companion_status:" << '\n' << "{\n";
    str << "    dance_status: " << companion_status.dance_status << '\n';
    str << "    rssi_wifi: " << companion_status.rssi_wifi << '\n';
    str << "    rssi_xbee: " << companion_status.rssi_xbee << '\n';
    str << '}';
    return str;
}

} // namespace mavsdk